spring:
  webflux:
    base-path: /ms-transaction/v1
  application:
    name: transaction
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:transaction}
    username: postgres
    password: root
  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:transaction}
    user: postgres
    password: root
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        min.insync.replicas: 1
    consumer:
      group-id: "transaction-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: "templario01.io.transaction.adapter.input.event.dto.ValidatedTransactionEventInbound"
        spring.json.trusted.packages: "*"
        topic-name: "payment.transaction.status"
    properties:
      security.protocol: PLAINTEXT

jwt:
  secret: "tHLkq8INxZ6YXYOMHF7t+288sZNA6AVR1hN3b9VZtNE="

app:
  kafka:
    transfer-topic: "payment.transaction"
server:
  port: 3000
  error:
    include-stacktrace: never